### ISSUE TITLE
Windows not grouped by construction in WP if no PH frame assigned

### ISSUE THREAD

**Issue by TfedUD** [PH-Tools/honeybee_grasshopper_ph#1]
Hi! this is as much a reminder for me as a 'hey issue' but:
without the PH frame_, the windows are all one 'merged component' group in WP, 
it would be nice for a default frame, as if I add my 'fnone' to all my window constructions it works to group windows in WP
![image](https://user-images.githubusercontent.com/63176386/190497541-228fdd83-676e-438e-baff-8ca90bab9702.png)

**Comment by PH-Tools** [comment]
Hey @TfedUD , 
Yes I'm sure we can modify the defaults here. Right now it *should* be grouping windows by their Honeybee-Construction Type ([uses the HB 'identifier' of the HB-Construction to group the windows by type](https://github.com/PH-Tools/PHX/blob/346e2364e99c7d36efb4b4a1c32d0c0f56db62f5/PHX/from_HBJSON/create_assemblies.py#L228)):

```python
_project.window_types[hb_win_construction.identifier] = phx_aperture_constr
```

so then, in WUFI, any window with the same construction-identifer should get automatically grouped together into a single 'component' with multiple sub-faces. Is that not how its acting now?

**Comment by ed-p-may** [comment]
Should be resolved in current version
