### ISSUE TITLE
HBPH - Set Res Occupancy Not working 

### ISSUE THREAD

**Issue by TfedUD** [PH-Tools/honeybee_grasshopper_ph#26]
Model is at video stage 07 HBPH to WUFU-Passive
![image](https://github.com/PH-Tools/honeybee_grasshopper_ph/assets/63176386/c8597d07-2097-4dd8-8592-4c8fdd4f52ac)

I can send the files if desired

**Comment by PH-Tools** [comment]
Thanks @TfedUD ,

I think I changed that component after making the video. I will need to update the video - thanks for flagging that. 

If you enter values that look like this:
<img width="854" alt="Screen Shot 2023-11-11 at 10 18 44 AM" src="https://github.com/PH-Tools/honeybee_grasshopper_ph/assets/69652712/9932c71d-8caa-497a-8a4a-db49080ea22b">

does it work properly for you?

**Comment by TfedUD** [comment]
Good to go when inputs are done properly! 
![image](https://github.com/PH-Tools/honeybee_grasshopper_ph/assets/63176386/114f0b47-84d1-4151-99b3-69c47e3dec5d)
Thank you!
